# pylint: disable=C0114,C0103
from enum import Enum
from .logger import log


# https://github.com/EternalWraith/PalEdit/blob/main/PalInfo.py
class PalType(Enum):
    """PalSkills

    See:
        https://github.com/EternalWraith/PalEdit/blob/main/PalInfo.py
        https://github.com/EternalWraith/PalEdit/blob/main/palworld_pal_edit/resources/data/pals.json

    Args:
        Enum (str):  Name of pal per internal ID.
    """
    Alpaca = "Melpaca"
    AmaterasuWolf = "Kitsun"
    Anubis = "Anubis"
    Baphomet = "Incineram"
    Baphomet_Dark = "Incineram Noct"
    Bastet = "Mau"
    Bastet_Ice = "Mau Cryst"
    BerryGoat = "Caprity"
    BirdDragon = "Vanwyrm"
    BirdDragon_Ice = "Vanwyrm Cryst"
    BlackCentaur = "Necromus"
    BlackGriffon = "Shadowbeak"
    BlackMetalDragon = "Astegon"
    BlueDragon = "Azurobe"
    BluePlatypus = "Fuack"
    Boar = "Rushoar"
    CaptainPenguin = "Penking"
    Carbunclo = "Lifmunk"
    CatBat = "Tombat"
    CatMage = "Katress"
    CatVampire = "Felbat"
    ChickenPal = "Chikipi"
    ColorfulBird = "Tocotoco"
    CowPal = "Mozzarina"
    CuteButterfly = "Cinnamoth"
    CuteFox = "Vixy"
    CuteMole = "Fuddler"
    DarkCrow = "Cawgnito"
    DarkScorpion = "Menasting"
    Deer = "Eikthyrdeer"
    Deer_Ground = "Eikthyrdeer Terra"
    DreamDemon = "Daedream"
    DrillGame = "Digtoise"
    Eagle = "Galeclaw"
    ElecCat = "Sparkit"
    ElecPanda = "Grizzbolt"
    FairyDragon = "Elphidran"
    FairyDragon_Water = "Elphidran Aqua"
    FengyunDeeper = "Fenglope"
    FireKirin = "Pyrin"
    FireKirin_Dark = "Pyrin Noct"
    FlameBambi = "Rooby"
    FlameBuffalo = "Arsox"
    FlowerDinosaur = "Dinossom"
    FlowerDinosaur_Electric = "Dinossom Lux"
    FlowerDoll = "Petallia"
    FlowerRabbit = "Flopie"
    FlyingManta = "Celaray"
    FoxMage = "Wixen"
    Ganesha = "Teafant"
    Garm = "Direhowl"
    GhostBeast = "Maraith"
    Gorilla = "Gorirat"
    GrassMammoth = "Mammorest"
    GrassMammoth_Ice = "Mammorest Cryst"
    GrassPanda = "Mossanda"
    GrassPanda_Electric = "Mossanda Lux"
    GrassRabbitMan = "Verdash"
    HadesBird = "Helzephyr"
    HawkBird = "Nitewing"
    Hedgehog = "Jolthog"
    Hedgehog_Ice = "Jolthog Cryst"
    HerculesBeetle = "Warsect"
    Horus = "Faleris"
    IceDeer = "Reindrix"
    IceFox = "Foxcicle"
    IceHorse = "Frostallion"
    IceHorse_Dark = "Frostallion Noct"
    JetDragon = "Jetragon"
    Kelpie = "Kelpsea"
    Kelpie_Fire = "Kelpsea Ignis"
    KingAlpaca = "Kingpaca"
    KingAlpaca_Ice = "Ice Kingpaca"
    KingBahamut = "Blazamut"
    Kirin = "Univolt"
    Kitsunebi = "Foxparks"
    LavaGirl = "Flambelle"
    LazyCatfish = "Dumud"
    LazyDragon = "Relaxaurus"
    LazyDragon_Electric = "Relaxaurus Lux"
    LilyQueen = "Lyleen"
    LilyQueen_Dark = "Lyleen Noct"
    LittleBriarRose = "Bristla"
    LizardMan = "Leezpunk"
    LizardMan_Fire = "Leezpunk Ignis"
    Manticore = "Blazehowl"
    Manticore_Dark = "Blazehowl Noct"
    Monkey = "Tanzee"
    MopBaby = "Swee"
    MopKing = "Sweepa"
    Mutant = "Lunaris"
    NaughtyCat = "Grintale"
    NegativeKoala = "Depresso"
    NegativeOctopus = "Killamari"
    NightFox = "Nox"
    Penguin = "Pengullet"
    PinkCat = "Cattiva"
    PinkLizard = "Lovander"
    PinkRabbit = "Ribbuny"
    PlantSlime = "Gumoss"
    PlantSlime_Flower = "Gumoss Flora"
    QueenBee = "Elizabee"
    RaijinDaughter = "Dazzi"
    RedArmorBird = "Ragnahawk"
    RobinHood = "Robinquill"
    RobinHood_Ground = "Robinquill Terra"
    Ronin = "Bushi"
    SaintCentaur = "Paladius"
    SakuraSaurus = "Broncherry"
    SakuraSaurus_Water = "Broncherry Aqua"
    Serpent = "Surfent"
    Serpent_Ground = "Surfent Terra"
    SharkKid = "Gobfin"
    SharkKid_Fire = "Gobfin Ignis"
    Sheepball = "Lamball"
    SkyDragon = "Quivern"
    SoldierBee = "Beegarde"
    Suzaku = "Suzaku"
    Suzaku_Water = "Suzaku Aqua"
    SweetsSheep = "Woolipop"
    ThunderBird = "Beakon"
    ThunderDog = "Rayhound"
    ThunderDragonMan = "Orserk"
    Umihebi = "Jormuntide"
    Umihebi_Fire = "Jormuntide Ignis"
    VioletFairy = "Vaelet"
    VolcanicMonster = "Reptyro"
    VolcanicMonster_Ice = "Reptyro Cryst"
    WeaselDragon = "Chillet"
    Werewolf = "Loupmoon"
    WhiteMoth = "Sibelyx"
    WhiteTiger = "Cryolinx"
    WindChimes = "Hangyu"
    WindChimes_Ice = "Hangyu Cryst"
    WizardOwl = "Hoocrates"
    WoolFox = "Cremis"
    Yeti = "Wumpo"
    Yeti_Grass = "Wumpo Botan"

    # Tower Bosses
    GYM_ThunderDragonMan = "Axel & Orserk"
    GYM_LilyQueen = "Lily & Lyleen"
    GYM_Horus = "Marus & Faleris"
    GYM_BlackGriffon = "Victor & Shadowbeak"
    GYM_ElecPanda = "Zoe & Grizzbolt"

    # Human Entities (Not yet finished)
    Believer_Bat = "Free Pal Alliance Devout (Bat)"
    Believer_Bat_Invader = "Free Pal Alliance Devout (Bat Invader)"
    Believer_CrossBow = "Free Pal Alliance Devout (CrossBow)"
    Believer_CrossBow_Invader = "Free Pal Alliance Devout (CrossBow Invader)"
    Female_People02 = "Villager 2"
    Female_People03 = "Villager 3"
    Female_Soldier01 = "Expedition Survivor"
    FireCult_FlameThrower = "Brothers of the Eternal Pyre Martyr (FlameThrower)"
    FireCult_FlameThrower_Invader = "Brothers of the Eternal Pyre Martyr (FlameThrower)"
    FireCult_Rifle = "Brothers of the Eternal Pyre Martyr (Rifle)"
    FireCult_Rifle_Invader = "Brothers of the Eternal Pyre Martyr (Rifle Invader)"
    Guard_Rifle = "Free Pal Alliance Guard (Rifle)"
    Hunter_Bat = "Syndicate Thug (Bat)"
    Hunter_Bat_Invader = "Syndicate Thug (Bat)"
    Hunter_Fat_GatlingGun = "Syndicate Crusher"
    Hunter_Fat_GatlingGun_Invader = "Invader Syndicate Crusher"
    Hunter_FlameThrower = "Syndicate Cleaner"
    Hunter_FlameThrower_Invader = "Invader Syndicate Cleaner"
    Hunter_Grenade = "Syndicate Grenadier"
    Hunter_Grenade_Invader = "Invader Syndicate Grenadier"
    Hunter_Handgun = "Syndicate Thug (Handgun)"
    Hunter_Handgun_Invader = "Invader Syndicate Thug (Handgun)"
    Hunter_Rifle = "Syndicate Gunner"
    Hunter_Rifle_Invader = "Invader Syndicate Gunner"
    Hunter_RocketLauncher = "Syndicate Elite"
    Hunter_RocketLauncher_Invader = "Invader Syndicate Elite"
    Hunter_Shotgun = "Syndicate Hunter"
    Hunter_Shotgun_Invader = "Invader Syndicate Hunter"
    Male_DarkTrader01 = "Black Marketeer"
    Male_DesertPeople01 = "Villager Desert 1"
    Male_People02 = "Villager 4"
    Male_Scientist01_LaserRifle = "PAL Genetic Research Unit Executioner (LaserRifle)"
    Male_Scientist01_LaserRifle_Invader = (
        "PAL Genetic Research Unit Executioner (LaserRifle Invader)"
    )
    Male_Soldier01 = "Burly Merc"
    MobuCitizen = "Mobu Citizen"
    MobuCitizen_Male = "Mobu Citizen Male"
    PalDealer = "Pal Merchant (Desert)"
    PalDealer_Desert = "Pal Merchant(Desert)"
    PalDealer_Volcano = "Pal Merchant(Volcano)"
    PalTrader = "Pal Merchant (Volcano)"
    Police_Shotgun = "PIDF Elite"
    Police_Handgun = "PIDF Guard"
    Police_Rifle = "PIDF Infantry"
    RandomEventShop = "Wandering Merchant(Random)"
    SalesPerson = "Merchant"
    SalesPerson_Desert = "Wandering Merchant(Desert)"
    SalesPerson_Desert2 = "Wandering Merchant(Desert2)"
    SalesPerson_Volcano = "Wandering Merchant(Volcano)"
    SalesPerson_Volcano2 = "Wandering Merchant(Volcano2)"
    SalesPerson_Wander = "Wandering Merchant"
    Scientist_FlameThrower = "PAL Genetic Research Unit Executioner (FlameThrower)"
    Scientist_FlameThrower_Invader = (
        "PAL Genetic Research Unit Executioner (FlameThrower Invader)"
    )
    Visitor_Hunter_Rifle = "Syndicate Thug"

    @classmethod
    def get(cls, value: str, origin_value: str) -> str:
        """Gets the value original value from a string.

        Args:
            value (str): The enum key (uppercase) that you're trying to check.
            origin_value (str): The value you're trying to find of.

        Returns:
            str: The original `en` localized name of the enum.
        """
        for i in PalType:
            if i.name.upper() == value:
                return i.value
        log(f"PalType {origin_value} need to be translated", "WARN")
        return origin_value
